# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AidenCli < Formula
  desc "StackGen AI Agent CLI"
  homepage "https://stackgen.com/"
  version "0.1.20"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/aios-remote/v0.1.20/aiden-cli_0.1.20_darwin_amd64.tar.gz"
      sha256 "12e7043d4826826f215d65e52949a0045e1336891f72edb001b91e38fd7f366e"

      define_method(:install) do
        bin.install "aiden-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/aios-remote/v0.1.20/aiden-cli_0.1.20_darwin_arm64.tar.gz"
      sha256 "279ec172c080e5d45d2192f68d6fdf28d9c9ed96282fc5b761f8e8065b62e43d"

      define_method(:install) do
        bin.install "aiden-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/aios-remote/v0.1.20/aiden-cli_0.1.20_linux_amd64.tar.gz"
      sha256 "c0a1740583d653f731dc9082e90a8a2d13125ffc1cd791b2b34d549d04ae4205"
      define_method(:install) do
        bin.install "aiden-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/aios-remote/v0.1.20/aiden-cli_0.1.20_linux_arm64.tar.gz"
      sha256 "926ee64599db14fe953529c898f092060231a495d58471e84240ef9dedc84414"
      define_method(:install) do
        bin.install "aiden-cli"
      end
    end
  end
end
