# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AidenRunner < Formula
  desc "StackGen AI Agent CLI"
  homepage "https://stackgen.com/"
  version "0.1.79"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/aiden-runner/v0.1.79/aiden-runner_0.1.79_darwin_amd64.tar.gz"
      sha256 "6069d565b04595f0c3b932ff58fc115ef057e00ed5fd1d2f828702ad561f9456"

      define_method(:install) do
        bin.install "aiden-runner"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/aiden-runner/v0.1.79/aiden-runner_0.1.79_darwin_arm64.tar.gz"
      sha256 "84b96d776c66cb7d162d9d514a19287fd36bb3a5049914e7d9152c41928c40ec"

      define_method(:install) do
        bin.install "aiden-runner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/aiden-runner/v0.1.79/aiden-runner_0.1.79_linux_amd64.tar.gz"
      sha256 "67f1be38ddd5c193e2014da7a5d249858a89d2eecfcbf74e0db56da8b985e1ae"
      define_method(:install) do
        bin.install "aiden-runner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/aiden-runner/v0.1.79/aiden-runner_0.1.79_linux_arm64.tar.gz"
      sha256 "3e9a006dfdd9dce030e540ea55645acb98560fd066c2de49c1b212d8b1d44e0f"
      define_method(:install) do
        bin.install "aiden-runner"
      end
    end
  end
end
