# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AidenCli < Formula
  desc "StackGen AI Agent CLI"
  homepage "https://stackgen.com/"
  version "0.0.15"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/aios-remote/v0.0.15/stackgen-guild_0.0.15_darwin_amd64.tar.gz"
      sha256 "5f71cde37800567e36e779028dda67cdb3dd0651d0d4328e3d6b40c64b0a8fbf"

      define_method(:install) do
        bin.install "aiden-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/aios-remote/v0.0.15/stackgen-guild_0.0.15_darwin_arm64.tar.gz"
      sha256 "62987cbfcc740c7d26eee818800efbd0519e4cc56c4f1c194deabe3351e335b6"

      define_method(:install) do
        bin.install "aiden-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/aios-remote/v0.0.15/stackgen-guild_0.0.15_linux_amd64.tar.gz"
      sha256 "9e02b498b67cd147d47fc53b18a63b31b5922ee85e984a57cff744671eadbef9"
      define_method(:install) do
        bin.install "aiden-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/aios-remote/v0.0.15/stackgen-guild_0.0.15_linux_arm64.tar.gz"
      sha256 "588d8906b9fe3628d657a0e5b1a2c4a6570dc73f226386b68007d5ccdf5de478"
      define_method(:install) do
        bin.install "aiden-cli"
      end
    end
  end
end
