# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appcd < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://appcd.com/"
  version "0.19.0"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://appcd-public-releases.s3.us-east-2.amazonaws.com/binaries/v0.19.0/appcd_0.19.0_darwin_amd64.tar.gz"
      sha256 "305d71cbf5deeeb72d381acd5a3a17f15b6c3d86bb8566ba0a0a7eb759eaad2c"

      def install
        bin.install "appcd"
      end
    end
    on_arm do
      url "https://appcd-public-releases.s3.us-east-2.amazonaws.com/binaries/v0.19.0/appcd_0.19.0_darwin_arm64.tar.gz"
      sha256 "fca59ba08d81c6a841aa9d3ee7a07fde3e4648b4ef79a38c54a14d21de0c12e2"

      def install
        bin.install "appcd"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://appcd-public-releases.s3.us-east-2.amazonaws.com/binaries/v0.19.0/appcd_0.19.0_linux_amd64.tar.gz"
        sha256 "7cbf3c8bc3dd636895e2c003c67750868bdfb779d3cae1edc37d474f61e5b67c"

        def install
          bin.install "appcd"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://appcd-public-releases.s3.us-east-2.amazonaws.com/binaries/v0.19.0/appcd_0.19.0_linux_arm64.tar.gz"
        sha256 "8bd33c765d8aa8d3c5374164a84bfa5e466b2bfb41986d2c723b3fc2c143ae09"

        def install
          bin.install "appcd"
        end
      end
    end
  end
end
