# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appcd < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://appcd.com/"
  version "0.15.8"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://appcd-public-releases.s3.us-east-2.amazonaws.com/binaries/v0.15.8/appcd_0.15.8_darwin_amd64.tar.gz"
      sha256 "d2b0f03e6de7e99773f42043047ed0cd61e932f3ac8967cfab3517c001d2933b"

      def install
        bin.install "appcd"
      end
    end
    on_arm do
      url "https://appcd-public-releases.s3.us-east-2.amazonaws.com/binaries/v0.15.8/appcd_0.15.8_darwin_arm64.tar.gz"
      sha256 "f4344026b50be4c9991a1b85137f46442b0b0ba484dec2c079b1d910682e5f6d"

      def install
        bin.install "appcd"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://appcd-public-releases.s3.us-east-2.amazonaws.com/binaries/v0.15.8/appcd_0.15.8_linux_amd64.tar.gz"
        sha256 "17d70e35c16d0d4913833101326b2be959d9cf7058db00dd9d84f955b9593a02"

        def install
          bin.install "appcd"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://appcd-public-releases.s3.us-east-2.amazonaws.com/binaries/v0.15.8/appcd_0.15.8_linux_arm64.tar.gz"
        sha256 "73d525bc7600cceb9c8e4ea38f302975110c976c82eb4c7542d1af9e19010aef"

        def install
          bin.install "appcd"
        end
      end
    end
  end
end
