# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Appcd < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://appcd.com/"
  version "0.15.4"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/appcd-dev/appcd/releases/download/v0.15.4/appcd_0.15.4_darwin_amd64.tar.gz"
      sha256 "a257d3df4eaa1153e684e554f37e7895fa2db904f9573765137127eeb2770b28"

      def install
        bin.install "appcd"
      end
    end
    on_arm do
      url "https://github.com/appcd-dev/appcd/releases/download/v0.15.4/appcd_0.15.4_darwin_arm64.tar.gz"
      sha256 "9137818717e2dc8357d03f748a289b98643bd2a8378ca3ebc65589fb74e4d5cc"

      def install
        bin.install "appcd"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/appcd-dev/appcd/releases/download/v0.15.4/appcd_0.15.4_linux_amd64.tar.gz"
        sha256 "0d88cb1e3d7f51752f342690a4437651aad1f31a4f89cc7f92e4b6ae3ed7fbc6"

        def install
          bin.install "appcd"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/appcd-dev/appcd/releases/download/v0.15.4/appcd_0.15.4_linux_arm64.tar.gz"
        sha256 "8a245d96348bed24dd46659e0df51d789460ab022bb1b6d9fa60ccb2a98d470a"

        def install
          bin.install "appcd"
        end
      end
    end
  end
end
