# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cce < Formula
  desc "Extract cloud SDK usage from source code with tree-sitter"
  homepage "https://github.com/appcd-dev/cce"
  version "0.0.7"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/cce/v0.0.7/cce_0.0.7_darwin_amd64.tar.gz"
      sha256 "900eec490cea1819a7c37ca15e0ed22b7fd5d58d5f83c2730a5347d1f8a88cda"

      define_method(:install) do
        bin.install "cce"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/cce/v0.0.7/cce_0.0.7_darwin_arm64.tar.gz"
      sha256 "c6ae264fdd30265425a7ac3f362c1dd019cdf0235422fc54aa36ce023d5512a7"

      define_method(:install) do
        bin.install "cce"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/cce/v0.0.7/cce_0.0.7_linux_amd64.tar.gz"
      sha256 "8a6eba1d6813b1f8fa99cac98cddbf90e7954fb73940a4ad2a883289914ce1fb"
      define_method(:install) do
        bin.install "cce"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/cce/v0.0.7/cce_0.0.7_linux_arm64.tar.gz"
      sha256 "3521c793165353792dfc427e8752b757fd78fc913eba17289937a3d9e8fc4985"
      define_method(:install) do
        bin.install "cce"
      end
    end
  end
end
