# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cce < Formula
  desc "Extract cloud SDK usage from source code with tree-sitter"
  homepage "https://github.com/appcd-dev/cce"
  version "0.0.5"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/cce/v0.0.5/cce_0.0.5_darwin_amd64.tar.gz"
      sha256 "36e712a33bf55dc647c5965d05dc2a07ced324a20625744884658a61ff85bb3f"

      define_method(:install) do
        bin.install "cce"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/cce/v0.0.5/cce_0.0.5_darwin_arm64.tar.gz"
      sha256 "53b359392c3f6313da12fecd1a41754ba2d1c2443d9a6847ee8bd119e0b10185"

      define_method(:install) do
        bin.install "cce"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/cce/v0.0.5/cce_0.0.5_linux_amd64.tar.gz"
      sha256 "ba2252bfb8f83194d19067cacb9356686b542e3ba4b618e0d71a2a5818b97859"
      define_method(:install) do
        bin.install "cce"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/cce/v0.0.5/cce_0.0.5_linux_arm64.tar.gz"
      sha256 "74216a1b512174ca3d4c6b856bacc24a702a230277607512a36715b022831b5b"
      define_method(:install) do
        bin.install "cce"
      end
    end
  end
end
