# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloud2codeBeta < Formula
  desc "Convert your cloud resources to tfstate files"
  homepage "https://stackgen.com/"
  version "0.5.0-rc.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v0.5.0-rc.1/cloud2code-beta_0.5.0-rc.1_darwin_amd64.tar.gz"
      sha256 "b1fd4d536dff6e2e47eeb821e0a89a04138ce184e8cdb5c51aab3ae5af86529c"

      def install
        bin.install "cloud2code-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v0.5.0-rc.1/cloud2code-beta_0.5.0-rc.1_darwin_arm64.tar.gz"
      sha256 "b5c02e4e38106d76afbb4f3d64d2a1269572796f90d07f70bfc66675701b9e9c"

      def install
        bin.install "cloud2code-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v0.5.0-rc.1/cloud2code-beta_0.5.0-rc.1_linux_amd64.tar.gz"
      sha256 "22f6dc283789e537b9e22cd27815eb0405f014e3e36022bfc34cec2adde600d7"
      def install
        bin.install "cloud2code-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v0.5.0-rc.1/cloud2code-beta_0.5.0-rc.1_linux_arm64.tar.gz"
      sha256 "65d66093440a2297d3a49a7e1a740dccd28b04ad18a63714e04261e9868728df"
      def install
        bin.install "cloud2code-beta"
      end
    end
  end
end
