# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloud2codeBetaAT051Rc1 < Formula
  desc "Convert your cloud resources to tfstate files"
  homepage "https://stackgen.com/"
  version "0.5.1-rc.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v0.5.1-rc.1/cloud2code-beta_0.5.1-rc.1_darwin_amd64.tar.gz"
      sha256 "a7cbf3cfadff1881d2d08c9815210c3d2e621c424e2662b8116e55b8528ab423"

      define_method(:install) do
        bin.install "cloud2code-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v0.5.1-rc.1/cloud2code-beta_0.5.1-rc.1_darwin_arm64.tar.gz"
      sha256 "13e321ddcbf4dd64d20abf752fe77c097f5161e280f5bd840fafcdda824318fd"

      define_method(:install) do
        bin.install "cloud2code-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v0.5.1-rc.1/cloud2code-beta_0.5.1-rc.1_linux_amd64.tar.gz"
      sha256 "9e8c217ada020e01e3a234427eca9cf550df86e6c8cc0c6117081fd5382bc0cd"
      define_method(:install) do
        bin.install "cloud2code-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v0.5.1-rc.1/cloud2code-beta_0.5.1-rc.1_linux_arm64.tar.gz"
      sha256 "7280270eac8e3e90587a7ffbca334e33c6bd89ef998b7fe187a7eff0aeb927e1"
      define_method(:install) do
        bin.install "cloud2code-beta"
      end
    end
  end
end
