# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloud2codeBetaAT050Rc5 < Formula
  desc "Convert your cloud resources to tfstate files"
  homepage "https://stackgen.com/"
  version "0.5.0-rc.5"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v0.5.0-rc.5/cloud2code-beta_0.5.0-rc.5_darwin_amd64.tar.gz"
      sha256 "9502f69dd9fd31c106cf3683fb465d335576e6d3323dd0ad869686cabe189f3a"

      def install
        bin.install "cloud2code-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v0.5.0-rc.5/cloud2code-beta_0.5.0-rc.5_darwin_arm64.tar.gz"
      sha256 "6fe1eb9c391019a689bea966237aa976f8abd8dbd9c71df0f5389824e583a99b"

      def install
        bin.install "cloud2code-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v0.5.0-rc.5/cloud2code-beta_0.5.0-rc.5_linux_amd64.tar.gz"
      sha256 "e46b8d249a9878041ca105beaaae05db862e537452234c32b6d428576346821d"
      def install
        bin.install "cloud2code-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v0.5.0-rc.5/cloud2code-beta_0.5.0-rc.5_linux_arm64.tar.gz"
      sha256 "70c4fb5d59a20af498cbd4a011f92405a97a76edc29d7f27156024a8c00e81e1"
      def install
        bin.install "cloud2code-beta"
      end
    end
  end
end
