# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloud2code < Formula
  desc "Convert your cloud resources to tfstate files"
  homepage "https://stackgen.com/"
  version "0.5.4"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/cloud2code/v0.5.4/cloud2code_0.5.4_darwin_amd64.tar.gz"
      sha256 "09cb5b3703916fb6547aa8576f0198783c0fbca3c11c3e3bfefd573be624d6a4"

      define_method(:install) do
        bin.install "cloud2code"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/cloud2code/v0.5.4/cloud2code_0.5.4_darwin_arm64.tar.gz"
      sha256 "d2c87ff246ccb54ad8927baaa8b0bee35097384d13ce443d48366ff77fabcc94"

      define_method(:install) do
        bin.install "cloud2code"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/cloud2code/v0.5.4/cloud2code_0.5.4_linux_amd64.tar.gz"
      sha256 "3e0bebe375d54161f03e8ac7975788818d7f3b074fa345af9584a9eddc37d7ba"
      define_method(:install) do
        bin.install "cloud2code"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/cloud2code/v0.5.4/cloud2code_0.5.4_linux_arm64.tar.gz"
      sha256 "0fa91aecef0cc6b03359a0cf3cccebd31369888843957f688149165623448e3e"
      define_method(:install) do
        bin.install "cloud2code"
      end
    end
  end
end
