# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genie < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "0.1.2-rc.2"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/genie/v0.1.2-rc.2/genie_0.1.2-rc.2_darwin_amd64.tar.gz"
      sha256 "aad7fc5bdf676d21d3edc26a01a80a299caaf4c6ab75beae09f52b61992e5285"

      def install
        bin.install "genie"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/genie/v0.1.2-rc.2/genie_0.1.2-rc.2_darwin_arm64.tar.gz"
      sha256 "13aeeff41bc6fe982181309795c44d3869363cd0b247d5527a5ee53adda08e95"

      def install
        bin.install "genie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/genie/v0.1.2-rc.2/genie_0.1.2-rc.2_linux_amd64.tar.gz"
      sha256 "8ea9a094152ce2e5806498d905e4cc292f396523ecf0b0a67da6ec895cf2e635"
      def install
        bin.install "genie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/genie/v0.1.2-rc.2/genie_0.1.2-rc.2_linux_arm64.tar.gz"
      sha256 "57aca5547eff17a3d1dc06cd0198bca8001a34a2fc8c8da6c411af85a36b0908"
      def install
        bin.install "genie"
      end
    end
  end
end
