# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GenieBeta < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "0.1.8-rc.5"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/genie-beta/v0.1.8-rc.5/genie_0.1.8-rc.5_darwin_amd64.tar.gz"
      sha256 "34d3cde1db30b9eaa215ad25ee954826d1fd53d198e3ecc8f01518863c081915"

      def install
        bin.install "genie-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/genie-beta/v0.1.8-rc.5/genie_0.1.8-rc.5_darwin_arm64.tar.gz"
      sha256 "5a8bd33aa4b2c6f9b305c1927ec16ba12fcecc4a3c388587057b5c8607b9ddd4"

      def install
        bin.install "genie-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/genie-beta/v0.1.8-rc.5/genie_0.1.8-rc.5_linux_amd64.tar.gz"
      sha256 "c1a830bc374f7a4227917ec45b3ca076a68d79cebf21a3e35e841b6f7e2fd539"
      def install
        bin.install "genie-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/genie-beta/v0.1.8-rc.5/genie_0.1.8-rc.5_linux_arm64.tar.gz"
      sha256 "8b9d1d1cb9cc49578cfbfa814237fe45359c5a9d54a778ca0c0156b3634bc226"
      def install
        bin.install "genie-beta"
      end
    end
  end
end
