# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genie < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "0.1.4"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/genie/v0.1.4/genie_0.1.4_darwin_amd64.tar.gz"
      sha256 "0e8359985a0eaae4a5f0959128ac3dfac10e1e8edb7d863c4fa8d5a430efe57d"

      def install
        bin.install "genie"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/genie/v0.1.4/genie_0.1.4_darwin_arm64.tar.gz"
      sha256 "24775b24a37a630320047c6650ee9fd8d723554fcb3932bd0e70189f60052e43"

      def install
        bin.install "genie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/genie/v0.1.4/genie_0.1.4_linux_amd64.tar.gz"
      sha256 "b484ee91c32064c1e163b00f8be8065bc1fa3aff53ee9da2e509a835b4d22a0d"
      def install
        bin.install "genie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/genie/v0.1.4/genie_0.1.4_linux_arm64.tar.gz"
      sha256 "78581ec5c1e6c9acbbfad67eb9f25d7666aa0c60c2c4692f2629124148baa680"
      def install
        bin.install "genie"
      end
    end
  end
end
