# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genie < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "0.1.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/genie/v0.1.0/genie_0.1.0_darwin_amd64.tar.gz"
      sha256 "c09116040095d2172b1f2ba20f18ce9b1f28afe3729c2f92e01daa3cf43424e0"

      def install
        bin.install "genie"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/genie/v0.1.0/genie_0.1.0_darwin_arm64.tar.gz"
      sha256 "7945ec163b657c7be4181e066cd7fdd428ca0110823ab9935f20e1afbd53c194"

      def install
        bin.install "genie"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/genie/v0.1.0/genie_0.1.0_linux_amd64.tar.gz"
      sha256 "c5576c7fb4c11398c2bbd04c37e95bfc7a1eaa919413d6aed1a3b208488d3f2b"
      def install
        bin.install "genie"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/genie/v0.1.0/genie_0.1.0_linux_arm64.tar.gz"
      sha256 "c17605247d6a2e7b4ad7048e117954fa3dc4fe045e7ca865a85f7d66d478e765"
      def install
        bin.install "genie"
      end
    end
  end
end
