# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GenieBeta < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "0.0.13-rc.4"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/genie-beta/v0.0.13-rc.4/stackgen-genie_0.0.13-rc.4_darwin_amd64.tar.gz"
      sha256 "ab271d7c67aac0e92ba50cadbf92226c728bf5b1eb986076a93a0703eaffce75"

      def install
        bin.install "genie-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/genie-beta/v0.0.13-rc.4/stackgen-genie_0.0.13-rc.4_darwin_arm64.tar.gz"
      sha256 "f48552726a0ab7a88caab066ea8278270748fcc35298fcadd0d5fc906aa3a658"

      def install
        bin.install "genie-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/genie-beta/v0.0.13-rc.4/stackgen-genie_0.0.13-rc.4_linux_amd64.tar.gz"
      sha256 "bf5b8e6f35229f8d21db836673ca8ad86a999c9c524859f3d4465171821e09e7"
      def install
        bin.install "genie-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/genie-beta/v0.0.13-rc.4/stackgen-genie_0.0.13-rc.4_linux_arm64.tar.gz"
      sha256 "3873f3a5d0d6c1e9ff726c46b539bd80594550ec6574b3c1689b23e5fc5f4edf"
      def install
        bin.install "genie-beta"
      end
    end
  end
end
