# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logexplorer < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "1.0.11"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/logexplorer/v1.0.11/grafana-logexplorer-app_1.0.11_darwin_amd64.tar.gz"
      sha256 "0458718cb5e7c58e3b278acf21247f1e446084fc973975d39e1703984dad5bbc"

      def install
        bin.install "logexplorer"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/logexplorer/v1.0.11/grafana-logexplorer-app_1.0.11_darwin_arm64.tar.gz"
      sha256 "134e09f7054f279dc1a522affd506bf139d4b320220f5a8cb226f07e2451e617"

      def install
        bin.install "logexplorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/logexplorer/v1.0.11/grafana-logexplorer-app_1.0.11_linux_amd64.tar.gz"
      sha256 "99bc7e90fd6ee8538b33cd642883f847e7b3a060996c9466c89cc2e3c9341698"
      def install
        bin.install "logexplorer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/logexplorer/v1.0.11/grafana-logexplorer-app_1.0.11_linux_arm64.tar.gz"
      sha256 "dfa6ef9b23c4b8f195fbc930d3b5a82ed5e0bfb9183e80e97fdb8a850a2efc9d"
      def install
        bin.install "logexplorer"
      end
    end
  end
end
