# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
#
# Placeholder formula — seeds the tap so GoReleaser can update it on the first
# tagged release of appcd-dev/pilot. Managed automatically by GoReleaser
# (see https://github.com/appcd-dev/pilot/blob/main/.goreleaser.yml).
class Pilot < Formula
  desc "StackGen Pilot: CLI-first SRE operational experience"
  homepage "https://github.com/appcd-dev/pilot"
  version "0.0.0-dev"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/appcd-dev/pilot/releases/download/v0.0.0/pilot_0.0.0_darwin_amd64.zip"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"

      def install
        bin.install "pilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/appcd-dev/pilot/releases/download/v0.0.0/pilot_0.0.0_darwin_arm64.zip"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"

      def install
        bin.install "pilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/appcd-dev/pilot/releases/download/v0.0.0/pilot_0.0.0_linux_amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      def install
        bin.install "pilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/appcd-dev/pilot/releases/download/v0.0.0/pilot_0.0.0_linux_arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      def install
        bin.install "pilot"
      end
    end
  end

  test do
    assert_match "pilot", shell_output("#{bin}/pilot --version")
  end
end
