# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StackgenSlo < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "1.30.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/stackgen-slo/v1.30.0/stackgen-slo-app_1.30.0_darwin_amd64.tar.gz"
      sha256 "91669cc01feea485d74e7a4b6cde53871fb6a5da5b02b88a6e56c944bf44fcf7"

      def install
        bin.install "stackgen-slo"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/stackgen-slo/v1.30.0/stackgen-slo-app_1.30.0_darwin_arm64.tar.gz"
      sha256 "186f6b308742dca422aa215eff5dadc477673ec3d1af79a1612b1f73fcbe67aa"

      def install
        bin.install "stackgen-slo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/stackgen-slo/v1.30.0/stackgen-slo-app_1.30.0_linux_amd64.tar.gz"
      sha256 "be425e6aed3800e25b5774b4b44557e3ca9aaf7fc8482cedc9c80de01facde41"
      def install
        bin.install "stackgen-slo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/stackgen-slo/v1.30.0/stackgen-slo-app_1.30.0_linux_arm64.tar.gz"
      sha256 "253da1a74ab2510d2ebd432ee22266db4896a191db6f316d3c65dac769ad65ac"
      def install
        bin.install "stackgen-slo"
      end
    end
  end
end
