# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StackgenSlo < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "1.48.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/stackgen-slo/v1.48.0/stackgen-slo-app_1.48.0_darwin_amd64.tar.gz"
      sha256 "6c483bd0d1fc514dcc44bc41030ef48ae3bdcae30aeb7745504514ed6c7e626c"

      define_method(:install) do
        bin.install "stackgen-slo"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/stackgen-slo/v1.48.0/stackgen-slo-app_1.48.0_darwin_arm64.tar.gz"
      sha256 "fe50b77840e6bd09955841e2951e941a6d1487e434e4165da1e4e51c9d19b6c8"

      define_method(:install) do
        bin.install "stackgen-slo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/stackgen-slo/v1.48.0/stackgen-slo-app_1.48.0_linux_amd64.tar.gz"
      sha256 "f3551dca88d0f1f3bae1ead572836b6a8010013bccd53d5301fdc638c8ad4f0a"
      define_method(:install) do
        bin.install "stackgen-slo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/stackgen-slo/v1.48.0/stackgen-slo-app_1.48.0_linux_arm64.tar.gz"
      sha256 "b125eca9c518cd3841bd14a686dbcb024ab4a7f8fc835e477c9c06b2c0ab33f5"
      define_method(:install) do
        bin.install "stackgen-slo"
      end
    end
  end
end
