# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StackgenBeta < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "0.75.0-rc.2"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/stackgen-cli/rc/v0.75.0-rc.2/stackgen-beta_0.75.0-rc.2_darwin_amd64.tar.gz"
      sha256 "f435f62998aec6bba2b7ba5eab75a09922cf7f3017c8ec7bcc577c7e45f20d26"

      define_method(:install) do
        bin.install "stackgen-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/stackgen-cli/rc/v0.75.0-rc.2/stackgen-beta_0.75.0-rc.2_darwin_arm64.tar.gz"
      sha256 "cce513fbaaf5adb672e176f9f1c632f321ba58c73c750270a635a44015410590"

      define_method(:install) do
        bin.install "stackgen-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/stackgen-cli/rc/v0.75.0-rc.2/stackgen-beta_0.75.0-rc.2_linux_amd64.tar.gz"
      sha256 "501508efa88418270cf5192549aa259f4576831e043be43c02e402eb1596fca5"
      define_method(:install) do
        bin.install "stackgen-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/stackgen-cli/rc/v0.75.0-rc.2/stackgen-beta_0.75.0-rc.2_linux_arm64.tar.gz"
      sha256 "5c8082b180aafaf69f8b2ad19386791868022d117a563c342eda17b5cbfae452"
      define_method(:install) do
        bin.install "stackgen-beta"
      end
    end
  end
end
