# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackgen < Formula
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "0.35.2"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/v0.35.2/appcd_0.35.2_darwin_amd64.tar.gz"
      sha256 "2f92c7b60af3a74f5fc9d3b61b4f3c20d727c4fb33a5bb2898c8ff851044bba2"

      def install
        bin.install "stackgen"
      end
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/v0.35.2/appcd_0.35.2_darwin_arm64.tar.gz"
      sha256 "2a8978bef7c254d91625635c73e20b0ce2dc032afd96ee8193ae34a898a2df03"

      def install
        bin.install "stackgen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.stackgen.com/binaries/v0.35.2/appcd_0.35.2_linux_amd64.tar.gz"
        sha256 "ea4af2f23a6ab4b2bc37a7c7c4bad308b6963d08b9b16a0f9806d7e048de5442"

        def install
          bin.install "stackgen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.stackgen.com/binaries/v0.35.2/appcd_0.35.2_linux_arm64.tar.gz"
        sha256 "f25acd32471fa0d48436cfbd8ea997ec4f702d02c15259b828796a5ee343c761"

        def install
          bin.install "stackgen"
        end
      end
    end
  end
end
