# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformImporterCli < Formula
  desc "Parsing Terraform Infrastructure as Code (IaC) files and importing them into Stackgen"
  homepage "https://stackgen.com/"
  version "0.1.21"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/v0.1.21/terraform-importer-cli_0.1.21_darwin_amd64.tar.gz"
      sha256 "0a23601015adf1370e88ff2dbce0262783ecafa5e097901d8b8f48e1890f3ac9"

      def install
        bin.install "terraform-importer"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/v0.1.21/terraform-importer-cli_0.1.21_darwin_arm64.tar.gz"
      sha256 "0437c9049338c0cc5a088fe4818c90fb5bc0e22444b63dfc5e51573893cdcc4b"

      def install
        bin.install "terraform-importer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/v0.1.21/terraform-importer-cli_0.1.21_linux_amd64.tar.gz"
      sha256 "84b73c200aea1a216bfbf83737bf69ab518a80175dd861da6369e6a275a6fa37"
      def install
        bin.install "terraform-importer"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/v0.1.21/terraform-importer-cli_0.1.21_linux_arm64.tar.gz"
      sha256 "0e61a237f4607024fc0c39066fe5440cbd42649aedd9978f70d9cc35b88f25ae"
      def install
        bin.install "terraform-importer"
      end
    end
  end
end
