# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformImporter < Formula
  desc "Parsing Terraform Infrastructure as Code (IaC) files and importing them into Stackgen"
  homepage "https://stackgen.com/"
  version "0.3.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/v0.3.0/terraform-importer-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "25be1638fa75512db7756bd9a655f1ec67343d83f0eef774a00a9ad962c3f17f"

      def install
        bin.install "terraform-importer"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/v0.3.0/terraform-importer-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "cbf9343871aa2654715e47bec9a07bb145272094a1ef146ad5677415691b19d4"

      def install
        bin.install "terraform-importer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/v0.3.0/terraform-importer-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "396d6edcab7dbb187c74e07e4073c33078be1fbe2428fd28a84149df25fb67b1"
      def install
        bin.install "terraform-importer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/v0.3.0/terraform-importer-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "02e702cf3c74224f355c2b47ea30afda6e21988fbb18ff416fcf759b866c3437"
      def install
        bin.install "terraform-importer"
      end
    end
  end
end
