# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformImporter < Formula
  desc "Parsing Terraform Infrastructure as Code (IaC) files and importing them into Stackgen"
  homepage "https://stackgen.com/"
  version "0.11.11"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.stackgen.com/binaries/v0.11.11/terraform-importer-cli_0.11.11_darwin_amd64.tar.gz"
      sha256 "2868f9074d9eee6a8f9bf699b61fdf616cac78e1e3f541de494a28825a9b0e3d"

      define_method(:install) do
        bin.install "terraform-importer"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.stackgen.com/binaries/v0.11.11/terraform-importer-cli_0.11.11_darwin_arm64.tar.gz"
      sha256 "77fbbe815ceeb6478d1ac8dbe6feeb726e75d762ebeb4d9435e27985ada827f4"

      define_method(:install) do
        bin.install "terraform-importer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/v0.11.11/terraform-importer-cli_0.11.11_linux_amd64.tar.gz"
      sha256 "a9b486b42dbe3b76e6f4b0fa1158b2c54cd334b0f0b522fff8bdf5f820f04730"
      define_method(:install) do
        bin.install "terraform-importer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.stackgen.com/binaries/v0.11.11/terraform-importer-cli_0.11.11_linux_arm64.tar.gz"
      sha256 "e4e34ba5c9045139360522c57073842dacd7f6dd314af247c5f1b399e4494fe1"
      define_method(:install) do
        bin.install "terraform-importer"
      end
    end
  end
end
