# This file was generated by GoReleaser. DO NOT EDIT.
cask "aiden-runner" do
  version "0.1.37"

  on_macos do
    on_intel do
      sha256 "7fec3d78a194b452f039ac4c2f47218994aeb72fcb3386ccfd0100df82395c4a"
      url "https://releases.stackgen.com/binaries/aiden-runner/v#{version}/aiden-runner_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "27a66a38a7921a6b0ae0078c08f655f84044bd22616824430d5759c28c89e830"
      url "https://releases.stackgen.com/binaries/aiden-runner/v#{version}/aiden-runner_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "aiden-runner"
  desc "StackGen AI Agent CLI"
  homepage "https://stackgen.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aiden-runner"

  # No zap stanza required

end
