# This file was generated by GoReleaser. DO NOT EDIT.
cask "aiden-cli" do
  version "0.1.20"

  on_macos do
    on_intel do
      sha256 "12e7043d4826826f215d65e52949a0045e1336891f72edb001b91e38fd7f366e"
      url "https://releases.stackgen.com/binaries/aios-remote/v#{version}/aiden-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "279ec172c080e5d45d2192f68d6fdf28d9c9ed96282fc5b761f8e8065b62e43d"
      url "https://releases.stackgen.com/binaries/aios-remote/v#{version}/aiden-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "aiden-cli"
  desc "StackGen AI Agent CLI"
  homepage "https://stackgen.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aiden-cli"

  # No zap stanza required

end
