# This file was generated by GoReleaser. DO NOT EDIT.
cask "aiden-runner" do
  version "0.1.62"

  on_macos do
    on_intel do
      sha256 "519a18236c6adb593e51abd15200ba429d610821556dbe15234e2e58464b9782"
      url "https://releases.stackgen.com/binaries/aiden-runner/v#{version}/aiden-runner_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "00ad4a0f6f7283552153eb0535c2ee9c095762793069177e79171d13ca80e8ae"
      url "https://releases.stackgen.com/binaries/aiden-runner/v#{version}/aiden-runner_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "aiden-runner"
  desc "StackGen AI Agent CLI"
  homepage "https://stackgen.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aiden-runner"

  # No zap stanza required

end
