# This file was generated by GoReleaser. DO NOT EDIT.
cask "aiden-runner" do
  version "0.2.22"

  on_macos do
    on_arm do
      sha256 "20f28b746563d66f27e5137efe4a3a0b42ed803541015582358dd3785c27ebc2"
      url "https://releases.stackgen.com/binaries/aiden-runner/v#{version}/aiden-runner_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c3e0d56e75b5693c97d1b6f0d78173dbd7b525fe33c7ea83b913c5c8023ca974"
      url "https://releases.stackgen.com/binaries/aiden-runner/v#{version}/aiden-runner_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "aiden-runner"
  desc "StackGen AI Agent CLI"
  homepage "https://stackgen.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aiden-runner"

  # No zap stanza required
end
