# This file was generated by GoReleaser. DO NOT EDIT.
cask "aiden-cli" do
  version "0.0.16"

  on_macos do
    on_intel do
      sha256 "bbe091da35aa838ee17b83287581dbfce20c72588b9826705f761d64ace25614"
      url "https://releases.stackgen.com/binaries/aios-remote/v#{version}/aiden-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "748827871a84ca34dcb1f1fdc0810f1376c6ea444101eef82b323bb039510378"
      url "https://releases.stackgen.com/binaries/aios-remote/v#{version}/aiden-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "aiden-cli"
  desc "StackGen AI Agent CLI"
  homepage "https://stackgen.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aiden-cli"

  # No zap stanza required

end
