# This file was generated by GoReleaser. DO NOT EDIT.
cask "aiden-cli" do
  version "0.1.21"

  on_macos do
    on_intel do
      sha256 "f6981486b9a595f4ada387313801bb827c29570db8f6ebaba4e905389c665f37"
      url "https://releases.stackgen.com/binaries/aios-remote/v#{version}/aiden-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a02393f6fa0623d2b26073b6fa27c0309435b1e82bb9aa6e8d60738dd3916fd"
      url "https://releases.stackgen.com/binaries/aios-remote/v#{version}/aiden-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "aiden-cli"
  desc "StackGen AI Agent CLI"
  homepage "https://stackgen.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aiden-cli"

  # No zap stanza required

end
