# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloud2code-beta" do
  name "cloud2code-beta"
  desc "Convert your cloud resources to tfstate files"
  homepage "https://stackgen.com/"
  version "0.4.5-rc.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloud2code-beta"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v#{version}/cloud2code-beta_#{version}_darwin_amd64.tar.gz"
      sha256 "23046240d7d7e07c1b49749369d998cd36ff64b35bfd79e81e2e2c50be9b154f"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v#{version}/cloud2code-beta_#{version}_darwin_arm64.tar.gz"
      sha256 "8da49214748e932e69c97d4eea2f507f77b4be2d8cff54d7899bbd171661055d"
    end
  end

  # No zap stanza required
end
