# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloud2code-beta@0.5.1-rc.1" do
  name "cloud2code-beta@0.5.1-rc.1"
  desc "Convert your cloud resources to tfstate files"
  homepage "https://stackgen.com/"
  version "0.5.1-rc.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloud2code-beta@0.5.1-rc.1"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v#{version}/cloud2code-beta_#{version}_darwin_amd64.tar.gz"
      sha256 "a7cbf3cfadff1881d2d08c9815210c3d2e621c424e2662b8116e55b8528ab423"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v#{version}/cloud2code-beta_#{version}_darwin_arm64.tar.gz"
      sha256 "13e321ddcbf4dd64d20abf752fe77c097f5161e280f5bd840fafcdda824318fd"
    end
  end

  # No zap stanza required
end
