# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloud2code" do
  name "cloud2code"
  desc "Convert your cloud resources to tfstate files"
  homepage "https://stackgen.com/"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloud2code"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/cloud2code/v#{version}/cloud2code_#{version}_darwin_amd64.tar.gz"
      sha256 "161cfe4eeedb893d5109d94d4c1edab6d58bb636c1e6400001c7b5173fe20690"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/cloud2code/v#{version}/cloud2code_#{version}_darwin_arm64.tar.gz"
      sha256 "d7aeba6f32e93ec395ebffd65a1b53f9f86388222a3af68b91627bda4ac30171"
    end
  end

  # No zap stanza required
end
