# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloud2code-beta" do
  name "cloud2code-beta"
  desc "Convert your cloud resources to tfstate files"
  homepage "https://stackgen.com/"
  version "0.4.5-rc.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloud2code-beta"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v#{version}/cloud2code-beta_#{version}_darwin_amd64.tar.gz"
      sha256 "f4a28c294a1bd59b4f4e324650c2a41f80ccf29d953cfc34d34700a68dc30c77"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v#{version}/cloud2code-beta_#{version}_darwin_arm64.tar.gz"
      sha256 "5a7504c277c7d1aca2be49485f2655eed6cfdb6401a68a9fef092e0ce869c936"
    end
  end

  # No zap stanza required
end
