# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloud2code-beta" do
  name "cloud2code-beta"
  desc "Convert your cloud resources to tfstate files"
  homepage "https://stackgen.com/"
  version "0.5.0-rc.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloud2code-beta"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v#{version}/cloud2code-beta_#{version}_darwin_amd64.tar.gz"
      sha256 "b1fd4d536dff6e2e47eeb821e0a89a04138ce184e8cdb5c51aab3ae5af86529c"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v#{version}/cloud2code-beta_#{version}_darwin_arm64.tar.gz"
      sha256 "b5c02e4e38106d76afbb4f3d64d2a1269572796f90d07f70bfc66675701b9e9c"
    end
  end

  # No zap stanza required
end
