# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloud2code" do
  version "0.5.14"

  on_macos do
    on_arm do
      sha256 "f47232a3a7310167865113b63f7a4c154cf004343190f348de75dfae3baef304"
      url "https://releases.stackgen.com/binaries/cloud2code/v#{version}/cloud2code_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9053ea2f27487a8ffaf90cd904843d0152d976532a9295961bf82c3cae6ef307"
      url "https://releases.stackgen.com/binaries/cloud2code/v#{version}/cloud2code_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "cloud2code"
  desc "Convert your cloud resources to tfstate files"
  homepage "https://stackgen.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloud2code"

  # No zap stanza required
end
