# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloud2code" do
  version "0.5.4"

  on_macos do
    on_arm do
      sha256 "d2c87ff246ccb54ad8927baaa8b0bee35097384d13ce443d48366ff77fabcc94"
      url "https://releases.stackgen.com/binaries/cloud2code/v#{version}/cloud2code_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "09cb5b3703916fb6547aa8576f0198783c0fbca3c11c3e3bfefd573be624d6a4"
      url "https://releases.stackgen.com/binaries/cloud2code/v#{version}/cloud2code_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "cloud2code"
  desc "Convert your cloud resources to tfstate files"
  homepage "https://stackgen.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloud2code"

  # No zap stanza required
end
