# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloud2code-beta@0.5.2-rc.2" do
  version "0.5.2-rc.2"

  on_macos do
    on_intel do
      sha256 "307e274284755bf060f9f82f1e4639be6ff3059f15ca3f1e6f38309a58804ee9"
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v#{version}/cloud2code-beta_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e25cf7d42efa9b805b14fbf08b1d3ea784b86d4239b8b703c21bcfa26292c4c2"
      url "https://releases.stackgen.com/binaries/cloud2code/rc/v#{version}/cloud2code-beta_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "cloud2code-beta@0.5.2-rc.2"
  desc "Convert your cloud resources to tfstate files"
  homepage "https://stackgen.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloud2code-beta@0.5.2-rc.2"

  # No zap stanza required

end
