# This file was generated by GoReleaser. DO NOT EDIT.
cask "logexplorer" do
  name "logexplorer"
  desc "Log Explorer"
  homepage "https://stackgen.com/"
  version "1.37.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logexplorer"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/logexplorer/v#{version}/grafana-logexplorer-app_#{version}_darwin_amd64.tar.gz"
      sha256 "7072ce870d21fd5f98f382a4320a99ed20e94e323765c9828d8edfb2e1cf9d5c"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/logexplorer/v#{version}/grafana-logexplorer-app_#{version}_darwin_arm64.tar.gz"
      sha256 "de82c716307bdccf751c765908562f965cc84af2f09dbe9760260b6bc4cb039b"
    end
  end

  # No zap stanza required
end
