# This file was generated by GoReleaser. DO NOT EDIT.
cask "logexplorer" do
  name "logexplorer"
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "1.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logexplorer"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/logexplorer/v#{version}/grafana-logexplorer-app_#{version}_darwin_amd64.tar.gz"
      sha256 "b39924511dc6dc4e47cb3bb8deb575e23f9e34c180c6a853270679ac023f24c6"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/logexplorer/v#{version}/grafana-logexplorer-app_#{version}_darwin_arm64.tar.gz"
      sha256 "f5ec285974d1d4ed4c6077d632edd0e0df22fcb9b7cf52faf45e724f6a6168d2"
    end
  end

  # No zap stanza required
end
