# This file was generated by GoReleaser. DO NOT EDIT.
cask "logexplorer" do
  name "logexplorer"
  desc "Log Explorer"
  homepage "https://stackgen.com/"
  version "1.58.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logexplorer"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/logexplorer/v#{version}/grafana-logexplorer-app_#{version}_darwin_amd64.tar.gz"
      sha256 "8745fcb894ae0825115e46d460d3ddffc2139ef3f39448a87967a4086d4b904e"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/logexplorer/v#{version}/grafana-logexplorer-app_#{version}_darwin_arm64.tar.gz"
      sha256 "fa8b72b7fff2909eb547e7bf7b083a50b9929a89625ee5efee2f16ea620289d3"
    end
  end

  # No zap stanza required
end
