# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackgen-beta" do
  version "0.79.0-rc.1"

  on_macos do
    on_intel do
      sha256 "04311f937709f2df799a4bc41b3c96a058797cd89787ceb92e5180d8bc501dfa"
      url "https://releases.stackgen.com/binaries/stackgen-cli/rc/v#{version}/stackgen-beta_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bfeebead6b68c7ddf025c94aa0e92f87cff25b162e2fd005d28e895acf7bab6"
      url "https://releases.stackgen.com/binaries/stackgen-cli/rc/v#{version}/stackgen-beta_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "stackgen-beta"
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackgen-beta"

  # No zap stanza required

end
