# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackgen" do
  name "stackgen"
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "0.74.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackgen"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/stackgen-cli/v#{version}/stackgen-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "b1cb03930b51ee2cd90bab2a5703a6c6322c7cdb7e9e911914d5e1140311d1b3"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/stackgen-cli/v#{version}/stackgen-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "81239c5d0c504e4d7926116e80734461b832c3a041c0d5504b23ba61fc2e6127"
    end
  end

  # No zap stanza required
end
