# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackgen-beta" do
  version "0.79.1-rc.1"

  on_macos do
    on_intel do
      sha256 "c5a62e41f2daff46db54487c314ab77a42f5c1097769976a6680d5f6ed3925fb"
      url "https://releases.stackgen.com/binaries/stackgen-cli/rc/v#{version}/stackgen-beta_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e019cb8f411ef54cd4481d0e54da2e8f0ae88f07b54edd0f442056fab5b3ce84"
      url "https://releases.stackgen.com/binaries/stackgen-cli/rc/v#{version}/stackgen-beta_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "stackgen-beta"
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackgen-beta"

  # No zap stanza required

end
