# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackgen-slo" do
  name "stackgen-slo"
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackgen-slo"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/stackgen-slo/v#{version}/stackgen-slo-app_#{version}_darwin_amd64.tar.gz"
      sha256 "9fa7d0e82312169ce195beb5c2093784a8f3fddfe86ce8cbb915b4ce02220e91"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/stackgen-slo/v#{version}/stackgen-slo-app_#{version}_darwin_arm64.tar.gz"
      sha256 "d6bde9d470812718a3fbf35ab9f34aba8fc65b52afa70e09d30486c349b6274b"
    end
  end

  # No zap stanza required
end
