# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackgen" do
  name "stackgen"
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "0.72.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackgen"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/stackgen-cli/v#{version}/stackgen-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "6f13ea3a6864628be985dd28bb28ee224dfb0f201c9ac66d83f369d9ce70222b"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/stackgen-cli/v#{version}/stackgen-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "1d98b2dd1920238cb3d7965a6e5938e5927d1ad09d57dc204a42e44831470b4d"
    end
  end

  # No zap stanza required
end
