# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackgen" do
  version "0.82.0"

  on_macos do
    on_intel do
      sha256 "60f8d6d235a3c645edb14a843f2dc318de5bef8abf2ec37b1ec372dd327cbc59"
      url "https://releases.stackgen.com/binaries/stackgen-cli/v#{version}/stackgen-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "eaabe6572291258d3cfc57c00cb8ee878d4a7331266854b56c0f2a70349fd2f6"
      url "https://releases.stackgen.com/binaries/stackgen-cli/v#{version}/stackgen-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "stackgen"
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackgen"

  # No zap stanza required

end
