# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackgen-beta" do
  name "stackgen-beta"
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "0.73.2-rc.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackgen-beta"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/stackgen-cli/rc/v#{version}/stackgen-beta_#{version}_darwin_amd64.tar.gz"
      sha256 "179c297182cae7f71a09d0fa5310e01db40c558078b054f4f7689d757ddb67c9"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/stackgen-cli/rc/v#{version}/stackgen-beta_#{version}_darwin_arm64.tar.gz"
      sha256 "f915e198434b876427acdd35cd8a12c676a2e31a71648821fed454ea33a7f8aa"
    end
  end

  # No zap stanza required
end
