# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackgen-slo" do
  name "stackgen-slo"
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "1.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackgen-slo"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/stackgen-slo/v#{version}/stackgen-slo-app_#{version}_darwin_amd64.tar.gz"
      sha256 "1f1137ef5016dfa4fb92c57827bb7f98f78a1e1fbbf39acd4aa3a452e55c9738"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/stackgen-slo/v#{version}/stackgen-slo-app_#{version}_darwin_arm64.tar.gz"
      sha256 "983d5ace5af3d8334a4e08a1e04b9c4dda5eaad10ab80353ddc7078679c0607f"
    end
  end

  # No zap stanza required
end
