# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackgen-slo" do
  name "stackgen-slo"
  desc "Generative Infrastructure from Code"
  homepage "https://stackgen.com/"
  version "1.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackgen-slo"

  on_macos do
    on_intel do
      url "https://releases.stackgen.com/binaries/stackgen-slo/v#{version}/stackgen-slo-app_#{version}_darwin_amd64.tar.gz"
      sha256 "ba7a05a218248553d1c0292e00e54285ac963c84f075eba0a6de04bbd73f9207"
    end
    on_arm do
      url "https://releases.stackgen.com/binaries/stackgen-slo/v#{version}/stackgen-slo-app_#{version}_darwin_arm64.tar.gz"
      sha256 "37dfe80750b75d77f0e0a1dbd79460242c335cda24d50c272845aefb48d4e7b0"
    end
  end

  # No zap stanza required
end
